### ISSUE TITLE
Command Suggestion

### ISSUE THREAD

**Issue by abhinav031** [pryme-svg/PrimeBot#1]
I’d like to suggest a command probably something like `[prefix]spaceimage <image_name>` that’d post the requested image in the chat. Using the NASA Image and Video Library api.

Links
[NASA api site](https://api.nasa.gov/)
[Documentation](https://images.nasa.gov/docs/images.nasa.gov_api_docs.pdf)

**Comment by pryme-svg** [comment]
I’ll look into it. Also been thinking of using https://apod.nasa.gov/apod/ap210102.html and just parsing for an image

**Comment by pryme-svg** [comment]
9403648cfa3b01724ef25eee52a1da21525abfcb

**Comment by pryme-svg** [comment]
Feature has been added, with date. Closing
