### ISSUE TITLE
Help command

### ISSUE THREAD

**Issue by abhinav031** [pryme-svg/PrimeBot#2]
![0C7AA86E-8135-42F6-8F62-B6A890148A50](https://user-images.githubusercontent.com/73749351/103617150-bb688080-4f53-11eb-9aeb-d384a3b519a1.jpeg)

Looks like some commands in the help command have a prefix but some don’t.

**Comment by pryme-svg** [comment]
Yeah I’m just a little lazy I’ll fix it tmrw
