### ISSUE TITLE
>rarbg links to 1337x and not RARGB.

### ISSUE THREAD

**Issue by diedoesmc** [pryme-svg/PrimeBot#5]
When I went to use the >rargb command, 1337x links came up instead. Is this a consolidation of both sites or an oversight?

**Comment by pryme-svg** [comment]
Fixed in https://github.com/pryme-svg/PrimeBot/commit/176162208ab8f4f2464fafd247f16a9f9a31a1a6

Could you try now?

**Comment by diedoesmc** [comment]
x Command raised an exception: TypeError: string indices must be integers. We got a bug.

**Comment by diedoesmc** [comment]
RARBG. Not RARGB. :kekega:
Anyways, issue is fixed. Thanks.
